name: Deploy to AWS

on:
  push:
    branches: ["main"]
env:
  CDK_VERSION: "2.126.0"
  AWS_ACCOUNT_ID: "267104850766"
  AWS_REGION: "us-east-1"
  API_KEY: "gfdgsdfgdfsbffv345sdfsdf" 
  APPLICATION_TAG: "selenium"
  APPLICATION_NAME: "selenium-lambda"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::267104850766:role/deployment-role"
          role-session-name: deployment-role
          aws-region: "us-east-1"

      - name: Bootstrap
        run: |
          . _CI/bootstrap.sh

      - name: Bootstrap CDK Environment
        run: npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://267104850766/us-east-1

      - name: Deploy
        run: |
          . _CI/deploy.sh
